//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Batch_OperatorTime : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _BatchId;
        public int BatchId
        {
            get { return _BatchId; }
            set
            {
                if (_BatchId != value)
                {
                    _BatchId = value;
                    OnPropertyChanged("BatchId");
                }
            }
        }
        private int _OperatorId;
        public int OperatorId
        {
            get { return _OperatorId; }
            set
            {
                if (_OperatorId != value)
                {
                    _OperatorId = value;
                    OnPropertyChanged("OperatorId");
                }
            }
        }
        private long _TimeElapsedTicks;
        public long TimeElapsedTicks
        {
            get { return _TimeElapsedTicks; }
            set
            {
                if (_TimeElapsedTicks != value)
                {
                    _TimeElapsedTicks = value;
                    OnPropertyChanged("TimeElapsedTicks");
                }
            }
        }
        private System.DateTime _DateCreated;
        public System.DateTime DateCreated
        {
            get { return _DateCreated; }
            set
            {
                if (_DateCreated != value)
                {
                    _DateCreated = value;
                    OnPropertyChanged("DateCreated");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
