//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Batch : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _ProductId;
        public int ProductId
        {
            get { return _ProductId; }
            set
            {
                if (_ProductId != value)
                {
                    _ProductId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private bool _Closed;
        public bool Closed
        {
            get { return _Closed; }
            set
            {
                if (_Closed != value)
                {
                    _Closed = value;
                    OnPropertyChanged("Closed");
                }
            }
        }
        private long _TimeElapsedTicks;
        public long TimeElapsedTicks
        {
            get { return _TimeElapsedTicks; }
            set
            {
                if (_TimeElapsedTicks != value)
                {
                    _TimeElapsedTicks = value;
                    OnPropertyChanged("TimeElapsedTicks");
                }
            }
        }
        private bool _Override;
        public bool Override
        {
            get { return _Override; }
            set
            {
                if (_Override != value)
                {
                    _Override = value;
                    OnPropertyChanged("Override");
                }
            }
        }
        private Nullable<int> _LowerLimitOverride;
        public Nullable<int> LowerLimitOverride
        {
            get { return _LowerLimitOverride; }
            set
            {
                if (_LowerLimitOverride != value)
                {
                    _LowerLimitOverride = value;
                    OnPropertyChanged("LowerLimitOverride");
                }
            }
        }
        private Nullable<int> _UpperLimitOverride;
        public Nullable<int> UpperLimitOverride
        {
            get { return _UpperLimitOverride; }
            set
            {
                if (_UpperLimitOverride != value)
                {
                    _UpperLimitOverride = value;
                    OnPropertyChanged("UpperLimitOverride");
                }
            }
        }
        private Nullable<int> _NominalOverride;
        public Nullable<int> NominalOverride
        {
            get { return _NominalOverride; }
            set
            {
                if (_NominalOverride != value)
                {
                    _NominalOverride = value;
                    OnPropertyChanged("NominalOverride");
                }
            }
        }
        private Nullable<int> _TareOverride;
        public Nullable<int> TareOverride
        {
            get { return _TareOverride; }
            set
            {
                if (_TareOverride != value)
                {
                    _TareOverride = value;
                    OnPropertyChanged("TareOverride");
                }
            }
        }
        private int _FiftyCount;
        public int FiftyCount
        {
            get { return _FiftyCount; }
            set
            {
                if (_FiftyCount != value)
                {
                    _FiftyCount = value;
                    OnPropertyChanged("FiftyCount");
                }
            }
        }
        private bool _IsLive;
        public bool IsLive
        {
            get { return _IsLive; }
            set
            {
                if (_IsLive != value)
                {
                    _IsLive = value;
                    OnPropertyChanged("IsLive");
                }
            }
        }
        private bool _Deleted;
        public bool Deleted
        {
            get { return _Deleted; }
            set
            {
                if (_Deleted != value)
                {
                    _Deleted = value;
                    OnPropertyChanged("Deleted");
                }
            }
        }
        private System.DateTime _DateCreated;
        public System.DateTime DateCreated
        {
            get { return _DateCreated; }
            set
            {
                if (_DateCreated != value)
                {
                    _DateCreated = value;
                    OnPropertyChanged("DateCreated");
                }
            }
        }
        private Nullable<System.DateTime> _DateClosed;
        public Nullable<System.DateTime> DateClosed
        {
            get { return _DateClosed; }
            set
            {
                if (_DateClosed != value)
                {
                    _DateClosed = value;
                    OnPropertyChanged("DateClosed");
                }
            }
        }
        private Nullable<System.DateTime> _DateDeleted;
        public Nullable<System.DateTime> DateDeleted
        {
            get { return _DateDeleted; }
            set
            {
                if (_DateDeleted != value)
                {
                    _DateDeleted = value;
                    OnPropertyChanged("DateDeleted");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
