//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Device : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private string _DeviceName;
        public string DeviceName
        {
            get { return _DeviceName; }
            set
            {
                if (_DeviceName != value)
                {
                    _DeviceName = value;
                    OnPropertyChanged("DeviceName");
                }
            }
        }
        private string _IpAddress;
        public string IpAddress
        {
            get { return _IpAddress; }
            set
            {
                if (_IpAddress != value)
                {
                    _IpAddress = value;
                    OnPropertyChanged("IpAddress");
                }
            }
        }
        private string _ApplicationName;
        public string ApplicationName
        {
            get { return _ApplicationName; }
            set
            {
                if (_ApplicationName != value)
                {
                    _ApplicationName = value;
                    OnPropertyChanged("ApplicationName");
                }
            }
        }
        private string _CurrentVersion;
        public string CurrentVersion
        {
            get { return _CurrentVersion; }
            set
            {
                if (_CurrentVersion != value)
                {
                    _CurrentVersion = value;
                    OnPropertyChanged("CurrentVersion");
                }
            }
        }
        private string _VersionOnServer;
        public string VersionOnServer
        {
            get { return _VersionOnServer; }
            set
            {
                if (_VersionOnServer != value)
                {
                    _VersionOnServer = value;
                    OnPropertyChanged("VersionOnServer");
                }
            }
        }
        private bool _AutoStartConfigured;
        public bool AutoStartConfigured
        {
            get { return _AutoStartConfigured; }
            set
            {
                if (_AutoStartConfigured != value)
                {
                    _AutoStartConfigured = value;
                    OnPropertyChanged("AutoStartConfigured");
                }
            }
        }
        private bool _RecycleRequested;
        public bool RecycleRequested
        {
            get { return _RecycleRequested; }
            set
            {
                if (_RecycleRequested != value)
                {
                    _RecycleRequested = value;
                    OnPropertyChanged("RecycleRequested");
                }
            }
        }
        private System.DateTime _DateCreated;
        public System.DateTime DateCreated
        {
            get { return _DateCreated; }
            set
            {
                if (_DateCreated != value)
                {
                    _DateCreated = value;
                    OnPropertyChanged("DateCreated");
                }
            }
        }
        private Nullable<System.DateTime> _DateOfLastPing;
        public Nullable<System.DateTime> DateOfLastPing
        {
            get { return _DateOfLastPing; }
            set
            {
                if (_DateOfLastPing != value)
                {
                    _DateOfLastPing = value;
                    OnPropertyChanged("DateOfLastPing");
                }
            }
        }
        private Nullable<System.DateTime> _DateOfLastRestart;
        public Nullable<System.DateTime> DateOfLastRestart
        {
            get { return _DateOfLastRestart; }
            set
            {
                if (_DateOfLastRestart != value)
                {
                    _DateOfLastRestart = value;
                    OnPropertyChanged("DateOfLastRestart");
                }
            }
        }
        private bool _IsDisplayDevice;
        public bool IsDisplayDevice
        {
            get { return _IsDisplayDevice; }
            set
            {
                if (_IsDisplayDevice != value)
                {
                    _IsDisplayDevice = value;
                    OnPropertyChanged("IsDisplayDevice");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
