//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class EntityType : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private string _EntityName;
        public string EntityName
        {
            get { return _EntityName; }
            set
            {
                if (_EntityName != value)
                {
                    _EntityName = value;
                    OnPropertyChanged("EntityName");
                }
            }
        }
        private string _EntityTypeName;
        public string EntityTypeName
        {
            get { return _EntityTypeName; }
            set
            {
                if (_EntityTypeName != value)
                {
                    _EntityTypeName = value;
                    OnPropertyChanged("EntityTypeName");
                }
            }
        }
        private int _EntityTypeId;
        public int EntityTypeId
        {
            get { return _EntityTypeId; }
            set
            {
                if (_EntityTypeId != value)
                {
                    _EntityTypeId = value;
                    OnPropertyChanged("EntityTypeId");
                }
            }
        }
        private bool _IsReferenceDataType;
        public bool IsReferenceDataType
        {
            get { return _IsReferenceDataType; }
            set
            {
                if (_IsReferenceDataType != value)
                {
                    _IsReferenceDataType = value;
                    OnPropertyChanged("IsReferenceDataType");
                }
            }
        }
        private string _DisplayName;
        public string DisplayName
        {
            get { return _DisplayName; }
            set
            {
                if (_DisplayName != value)
                {
                    _DisplayName = value;
                    OnPropertyChanged("DisplayName");
                }
            }
        }
        private int _SortOrder;
        public int SortOrder
        {
            get { return _SortOrder; }
            set
            {
                if (_SortOrder != value)
                {
                    _SortOrder = value;
                    OnPropertyChanged("SortOrder");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
