//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class ErrorLog : INotifyPropertyChanged
    {
        private int _ErrorID;
        public int ErrorID
        {
            get { return _ErrorID; }
            set
            {
                if (_ErrorID != value)
                {
                    _ErrorID = value;
                    OnPropertyChanged("ErrorID");
                }
            }
        }
        private Nullable<int> _DeviceId;
        public Nullable<int> DeviceId
        {
            get { return _DeviceId; }
            set
            {
                if (_DeviceId != value)
                {
                    _DeviceId = value;
                    OnPropertyChanged("DeviceId");
                }
            }
        }
        private string _ComputerName;
        public string ComputerName
        {
            get { return _ComputerName; }
            set
            {
                if (_ComputerName != value)
                {
                    _ComputerName = value;
                    OnPropertyChanged("ComputerName");
                }
            }
        }
        private Nullable<System.DateTime> _TimeOfError;
        public Nullable<System.DateTime> TimeOfError
        {
            get { return _TimeOfError; }
            set
            {
                if (_TimeOfError != value)
                {
                    _TimeOfError = value;
                    OnPropertyChanged("TimeOfError");
                }
            }
        }
        private string _CustomMessage;
        public string CustomMessage
        {
            get { return _CustomMessage; }
            set
            {
                if (_CustomMessage != value)
                {
                    _CustomMessage = value;
                    OnPropertyChanged("CustomMessage");
                }
            }
        }
        private string _Message;
        public string Message
        {
            get { return _Message; }
            set
            {
                if (_Message != value)
                {
                    _Message = value;
                    OnPropertyChanged("Message");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
