//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Operator : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private string _FirstName;
        public string FirstName
        {
            get { return _FirstName; }
            set
            {
                if (_FirstName != value)
                {
                    _FirstName = value;
                    OnPropertyChanged("FirstName");
                }
            }
        }
        private string _LastName;
        public string LastName
        {
            get { return _LastName; }
            set
            {
                if (_LastName != value)
                {
                    _LastName = value;
                    OnPropertyChanged("LastName");
                }
            }
        }
        private int _ShiftId;
        public int ShiftId
        {
            get { return _ShiftId; }
            set
            {
                if (_ShiftId != value)
                {
                    _ShiftId = value;
                    OnPropertyChanged("ShiftId");
                }
            }
        }
        private int _RefTypeId;
        public int RefTypeId
        {
            get { return _RefTypeId; }
            set
            {
                if (_RefTypeId != value)
                {
                    _RefTypeId = value;
                    OnPropertyChanged("RefTypeId");
                }
            }
        }
        private Nullable<System.DateTime> _DateCreated;
        public Nullable<System.DateTime> DateCreated
        {
            get { return _DateCreated; }
            set
            {
                if (_DateCreated != value)
                {
                    _DateCreated = value;
                    OnPropertyChanged("DateCreated");
                }
            }
        }
        private Nullable<System.DateTime> _DateDeleted;
        public Nullable<System.DateTime> DateDeleted
        {
            get { return _DateDeleted; }
            set
            {
                if (_DateDeleted != value)
                {
                    _DateDeleted = value;
                    OnPropertyChanged("DateDeleted");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
