//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Scale : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _ScaleNumber;
        public int ScaleNumber
        {
            get { return _ScaleNumber; }
            set
            {
                if (_ScaleNumber != value)
                {
                    _ScaleNumber = value;
                    OnPropertyChanged("ScaleNumber");
                }
            }
        }
        private Nullable<int> _OperatorId;
        public Nullable<int> OperatorId
        {
            get { return _OperatorId; }
            set
            {
                if (_OperatorId != value)
                {
                    _OperatorId = value;
                    OnPropertyChanged("OperatorId");
                }
            }
        }
        private string _NetConnectionIpAddress;
        public string NetConnectionIpAddress
        {
            get { return _NetConnectionIpAddress; }
            set
            {
                if (_NetConnectionIpAddress != value)
                {
                    _NetConnectionIpAddress = value;
                    OnPropertyChanged("NetConnectionIpAddress");
                }
            }
        }
        private string _ScaleIpAddress;
        public string ScaleIpAddress
        {
            get { return _ScaleIpAddress; }
            set
            {
                if (_ScaleIpAddress != value)
                {
                    _ScaleIpAddress = value;
                    OnPropertyChanged("ScaleIpAddress");
                }
            }
        }
        private bool _Slave;
        public bool Slave
        {
            get { return _Slave; }
            set
            {
                if (_Slave != value)
                {
                    _Slave = value;
                    OnPropertyChanged("Slave");
                }
            }
        }
        private Nullable<int> _SlaveOrder;
        public Nullable<int> SlaveOrder
        {
            get { return _SlaveOrder; }
            set
            {
                if (_SlaveOrder != value)
                {
                    _SlaveOrder = value;
                    OnPropertyChanged("SlaveOrder");
                }
            }
        }
        private bool _Active;
        public bool Active
        {
            get { return _Active; }
            set
            {
                if (_Active != value)
                {
                    _Active = value;
                    OnPropertyChanged("Active");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
