//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class UserDisplay : INotifyPropertyChanged
    {
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _ScaleNo;
        public int ScaleNo
        {
            get { return _ScaleNo; }
            set
            {
                if (_ScaleNo != value)
                {
                    _ScaleNo = value;
                    OnPropertyChanged("ScaleNo");
                }
            }
        }
        private string _OperatorName;
        public string OperatorName
        {
            get { return _OperatorName; }
            set
            {
                if (_OperatorName != value)
                {
                    _OperatorName = value;
                    OnPropertyChanged("OperatorName");
                }
            }
        }
        private string _TimeLoggedOn;
        public string TimeLoggedOn
        {
            get { return _TimeLoggedOn; }
            set
            {
                if (_TimeLoggedOn != value)
                {
                    _TimeLoggedOn = value;
                    OnPropertyChanged("TimeLoggedOn");
                }
            }
        }
        private decimal _PacksPerMin;
        public decimal PacksPerMin
        {
            get { return _PacksPerMin; }
            set
            {
                if (_PacksPerMin != value)
                {
                    _PacksPerMin = value;
                    OnPropertyChanged("PacksPerMin");
                }
            }
        }
        private int _NoOfPacks;
        public int NoOfPacks
        {
            get { return _NoOfPacks; }
            set
            {
                if (_NoOfPacks != value)
                {
                    _NoOfPacks = value;
                    OnPropertyChanged("NoOfPacks");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
