//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Globeweigh.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class vwOperatorRefData : INotifyPropertyChanged
    {
        private string _FullName;
        public string FullName
        {
            get { return _FullName; }
            set
            {
                if (_FullName != value)
                {
                    _FullName = value;
                    OnPropertyChanged("FullName");
                }
            }
        }
        private string _ShiftName;
        public string ShiftName
        {
            get { return _ShiftName; }
            set
            {
                if (_ShiftName != value)
                {
                    _ShiftName = value;
                    OnPropertyChanged("ShiftName");
                }
            }
        }
        private int _id;
        public int id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("id");
                }
            }
        }
        private int _RefTypeId;
        public int RefTypeId
        {
            get { return _RefTypeId; }
            set
            {
                if (_RefTypeId != value)
                {
                    _RefTypeId = value;
                    OnPropertyChanged("RefTypeId");
                }
            }
        }
        private int _ShiftId;
        public int ShiftId
        {
            get { return _ShiftId; }
            set
            {
                if (_ShiftId != value)
                {
                    _ShiftId = value;
                    OnPropertyChanged("ShiftId");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
